=== DanielaSMR/XSD/XSD2/cines.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
<xs:simpleType name="codigo">
    <xs:restriction base="xs:string">
        <xs:pattern value="[0]\_[0-9]{1,3}"/>
    </xs:restriction>
</xs:simpleType>
<xs:element name="cines">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="cine" minOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="pelicula">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="actores">
                                        <xs:complexType>
                                            <xs:choice minOccurs="1">
                                                <xs:element name="actriz" type="xs:string"/>
                                                <xs:element name="actor" type="xs:string"/>
                                            </xs:choice>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="titulo" type="xs:string"/>
                                    <xs:element name="anyo" type="xs:integer"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="direccion" type="xs:string"/>
                        <xs:element name="codigoCine" minOccurs="0" maxOccurs="1"> 
                            <xs:complexType>
                                <xs:attribute name="num" type="codigo"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence> 
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== DanielaSMR/XSD/XSD2/cines.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE cines [
    <!ELEMENT cines (cine)+>
    <!ELEMENT cine (nombre,pelicula+,direccion,codigoCine?)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT pelicula (actores,titulo,anyo)>
    <!ELEMENT actores (actriz?, actor?)*>
    <!ELEMENT actriz (#PCDATA)>
    <!ELEMENT actor (#PCDATA)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT anyo (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT codigoCine (#PCDATA)>
    <!ATTLIST codigoCine num NMTOKEN #REQUIRED>
]>-->
<cines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cines.xsd">
   <cine>
        <nombre>ABC</nombre>
        <pelicula>
            <actores>
                <actriz>Enma</actriz>
            </actores>
            <titulo>Matriz</titulo>
            <anyo>2004</anyo>
        </pelicula>
        <direccion>Calle Inventada 39</direccion>
    </cine>
    <cine>
        <nombre>ABC</nombre>
        <pelicula>
            <actores>
                <actor>Enma</actor>
            </actores>
            <titulo>Matriz</titulo>
            <anyo>2004</anyo>
        </pelicula>
        <direccion>Calle Inventada 39</direccion>
        <codigoCine num="0_2"/>
    </cine>
    <cine>
        <nombre>ABC</nombre>
        <pelicula>
            <actores>
                <actriz>Enma</actriz>
            </actores>
            <titulo>Matriz</titulo>
            <anyo>2004</anyo>
        </pelicula>
        <direccion>Calle Inventada 39</direccion>
        <codigoCine num="0_2"/>
    </cine>
    <cine>
        <nombre>ABC</nombre>
        <pelicula>
            <actores>
                <actriz>Enma</actriz>
            </actores>
            <titulo>Matriz</titulo>
            <anyo>2004</anyo>
        </pelicula>
        <direccion>Calle Inventada 39</direccion>
        <codigoCine num="0_2"/>
    </cine>
    <cine>
        <nombre>ABC</nombre>
        <pelicula>
            <actores>
                <actriz>Enma</actriz>
            </actores>
            <titulo>Matriz</titulo>
            <anyo>2004</anyo>
        </pelicula>
        <direccion>Calle Inventada 39</direccion>
        <codigoCine num="0_2"/>
    </cine>
</cines>
